name: Android Build
on: push
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: ilharp/sign-android-release@v2
      name: Sign APK
      id: sign_apk
      with:
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
    - name: Rename APK
      run: mv "${{ steps.sign_apk.outputs.signedFile }}" "${{ github.workspace }}/arithist.apk"
    - name: Create release and upload APK
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: ${{ github.workspace }}/arithist.apk
